name: Compile with SourceMod

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/LICENSE'
      - '**/.git*'
      - '**/*.smx'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/LICENSE'
      - '**/.git*'
      - '**/*.smx'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.13.x'
          version-file: ./filereload.sp

      - name: Compile plugins
        run: |
          for file in filereload.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i include $file
          done
          echo "===OUT FILES==="
          ls
          echo version = ${{ steps.setup_sp.outputs.plugin-version }}
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Move smx to plugins directory
        run: |
          mkdir -p plugins
          mv filereload.smx plugins/

      - name: Create scripting directory and move source code
        run: |
          mkdir -p scripting/filereload
          mv filereload.sp scripting/

      - name: Extract plugin version
        id: get_version
        run: |
          version=$(grep 'PLUGIN_VERSION' filereload.sp | head -n1 | sed 's/.*"\(.*\)".*/\1/')
          echo "PLUGIN_VERSION=$version" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "File Reloader ${{ env.PLUGIN_VERSION }}"
          path: |
            plugins/filereload.smx
            scripting/filereload.sp